name: Build and Release Electron App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: push_swap_visualizer/package-lock.json

      - name: Install dependencies
        working-directory: ./push_swap_visualizer
        run: npm ci

      - name: Build Electron app
        working-directory: ./push_swap_visualizer
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run make

      - name: Upload build artifacts - ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: push_swap_visualizer-build-${{ matrix.os }}
          path: push_swap_visualizer/out/make/
          if-no-files-found: error
